[package]
name = "tcp_implementation"
version = "0.1.0"
authors = ["David Gao <davidgao313@outlook.com>"]
edition = "2021"

[dependencies]
tun-tap = "0.1.2"
hex = "0.4"
hex_fmt = "0.3"
etherparse = "0.8"
